[package]
name = "pipewire-dbus"
version = "3.0.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43", default-features = false, features = [
    "rt",
    "macros",
] }
zbus = { version = "5.3", default-features = false, features = ["tokio"] }
pipewire = "0.10"
anyhow = "1"
log = { version = "0.4", default-features = false }
env_logger = { version = "0.11", default-features = false, features = [
    "auto-color",
] }
jzon = "0.12.5"
